### ISSUE TITLE
Can't get an answer

### ISSUE THREAD

**Issue by marklysze** [mbarinov/repogpt#5]
I've added a repository and tried to query it but I'm always getting the same response:
`I'm sorry, but I cannot provide information on how Ollama is used based on the provided context. If you have any other questions or need assistance with a different topic, feel free to ask!`

Repo: `https://github.com/xyflow/xyflow`

![image](https://github.com/user-attachments/assets/fc5fca3b-6289-4160-a86c-b1087da4736e)

The import appears to have worked correctly:
```
[2024-10-10T18:14:10.210Z] Starting indexing for repository ID: cm23mb9cu002asy58ktbdo045
[2024-10-10T18:19:00.155Z] Loaded 604 documents from https://github.com/xyflow/xyflow
[2024-10-10T18:19:00.239Z] Split into 1059 chunks
[2024-10-10T18:19:00.239Z] Storing 1059 chunks into the vector store
[2024-10-10T18:19:00.242Z] Deleted existing documents in namespace: cm23mb9cu002asy58ktbdo045
[2024-10-10T18:19:00.611Z] Created 1059 document records
[2024-10-10T18:19:09.907Z] Added models to the vector store
```

**Comment by marklysze** [comment]
Ah, sorry, I think I used the wrong repo for the questions. It may not have answers for that repo! I'll keep testing :).

**Comment by marklysze** [comment]
@mbarinov, I'll add this to this closed issue to avoid creating a new issue yet. Are you able to see if this repo works for you?

I get the following (after a while, it's a big repo):
`https://github.com/langflow-ai/langflow`

```
[2024-10-10T18:57:25.869Z] Updated repository status to NOT_STARTED for URL: https://github.com/langflow-ai/langflow
[2024-10-10T18:57:25.871Z] Error during indexing for repository ID cm23ncopp0kxfsy58vv8jmuoq: PrismaClientUnknownRequestError: 
Invalid `prisma.document.create()` invocation:


Error in batch request 557: Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(PostgresError { code: "22021", message: "invalid byte sequence for encoding \"UTF8\": 0x00", severity: "ERROR", detail: None, column: None, hint: None }), transient: false })
    at Mn.handleRequestError (/home/ms_code/repogpt/node_modules/.pnpm/@prisma+client@5.20.0_prisma@5.20.0/node_modules/@prisma/client/runtime/library.js:121:7943)
    at Mn.handleAndLogRequestError (/home/ms_code/repogpt/node_modules/.pnpm/@prisma+client@5.20.0_prisma@5.20.0/node_modules/@prisma/client/runtime/library.js:121:7061)
    at Mn.request (/home/ms_code/repogpt/node_modules/.pnpm/@prisma+client@5.20.0_prisma@5.20.0/node_modules/@prisma/client/runtime/library.js:121:6745)
    at async l (/home/ms_code/repogpt/node_modules/.pnpm/@prisma+client@5.20.0_prisma@5.20.0/node_modules/@prisma/client/runtime/library.js:130:9633) {
  clientVersion: '5.20.0'
}```

**Comment by mbarinov** [comment]
This update addresses the issue of null bytes (0x00) in input data that were causing Prisma database insertion errors and invalid requests to the OpenAI API. Can you confirm that the issue is resolved @marklysze? 

https://github.com/mbarinov/repogpt/commit/669548a655e43f24f726a6b506c48f5e80687ad3
